apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Remove the name field; the ApplicationSet will inject it.
  namespace: wordpress
spec:
  project: default
  source:
    chart: wordpress
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.1.11
    helm:
      releaseName: wordpress
  destination:
    # Remove the token so that ApplicationSet overwrites it.
    server: ""
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
