apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: wordpresss
spec:
  project: default
  source:
    chart: wordpress
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.1.11
    helm:
      releaseName: wordpress
  destination:
    server: '{{server}}'
    namespace: wordpress-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
