apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base-applications
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  general-bootstrap: "true"
          - git:
              repoURL: https://github.com/spiffaz/gitops.git
              revision: HEAD
              directories:
                - path: base-apps/*
  template:
    metadata:
      name: '{{name}}-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/spiffaz/gitops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
