apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-specific-configs
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/spiffaz/gitops.git
        revision: HEAD
        directories:
          - path: clusters/*/*/*
  template:
    metadata:
      name: '{{path.basename}}-{{path[1]}}-specific'
      labels:
        cluster: '{{path.basename}}'
        account: '{{path[1]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/spiffaz/gitops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{metadata.annotations.argocd.argoproj.io/server-addr}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true