apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-specific-configs-app-of-apps
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/spiffaz/gitops.git
              revision: HEAD
              directories:
                - path: "clusters/*/*/*/*/*"  # Match clusters/aws/accountname/accountid/clustername/manifest.yaml and clusters/azure/subscriptionname/resourcegroup/clustername/manifest.yaml

          - clusters: {}  # Get all registered clusters
        # Only create applications where directory cluster name matches ArgoCD cluster name
        template:
          metadata:
            annotations:
              argocd.argoproj.io/matrix-condition: '{{name}} == {{path[4]}}'
  template:
    metadata:
      name: '{{path[5]}}-{{path[4]}}-{{path[3]}}' # clustername-[accountid/resourcegroup]-[accountname/subscriptionname]
      labels:
        cluster: '{{name}}'
        accountId: '{{path[3]}}'
        accountName: '{{path[2]}}'
        cloud: '{{path[1]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/spiffaz/gitops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true