apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mlops-applications
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  mlops-workload: "true"
          - git:
              repoURL: https://github.com/spiffaz/gitops.git
              revision: HEAD
              directories:
                - path: workloads/mlops/*
  template:
    metadata:
      name: '{{name}}-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/spiffaz/gitops.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
            - values-{{name}}.yaml  # Cluster-specific values file
      destination:
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true