apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mlops-applications
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            mlops-workload: "true"
  template:
    metadata:
      name: '{{name}}-mlops'
    spec:
      project: default
      source:
        repoURL: https://github.com/spiffaz/gitops.git
        targetRevision: HEAD
        path: workloads/mlops
      destination:
        server: '{{server}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
