apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-cloud-clusters
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/spiffaz/gitops.git
              revision: HEAD
              directories:
                - path: "clusters/*/*/*/*"  # e.g. clusters/aws/accountname/accountid/spiff-1
          - clusters: {}
  template:
    metadata:
      name: '{{path[1]}}-{{path[2]}}-{{path[4]}}'
      labels:
        cloud: '{{path[1]}}'
        accountName: '{{path[2]}}'
        accountId: '{{path[3]}}'
        cluster: '{{path[4]}}'
    spec:
      project: default
      source:
        # Assuming your in‑repo manifest is part of a Helm chart or Kustomize overlay,
        # you might not include the manifest’s templated tokens here.
        repoURL: https://github.com/spiffaz/gitops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{server}}'  # Make sure the clusters generator outputs a token exactly named "server"
        namespace: wordpress   # This value is hardcoded here
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
