apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyter-research
  namespace: research
spec:
  chart:
    spec:
      chart: jupyter
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: jupyter
  interval: 1h
  values:
    singleuser:
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
